<a href="https://colab.research.google.com/github/OliverTai0118/ryanben/blob/main/20220716.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#20220709作業

In [1]:
!pip install gradio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.1 MB 17.8 MB/s 
     |████████████████████████████████| 57 kB 2.3 MB/s 
     |████████████████████████████████| 1.1 MB 54.5 MB/s 
     |████████████████████████████████| 84 kB 3.2 MB/s 
     |████████████████████████████████| 272 kB 48.1 MB/s 
     |████████████████████████████████| 212 kB 48.0 MB/s 
     |████████████████████████████████| 54 kB 2.6 MB/s 
     |████████████████████████████████| 2.3 MB 41.5 MB/s 
     |████████████████████████████████| 84 kB 3.3 MB/s 
     |████████████████████████████████| 140 kB 60.1 MB/s 
     |████████████████████████████████| 271 kB 57.2 MB/s 
     |████████████████████████████████| 144 kB 70.8 MB/s 
     |████████████████████████████████| 94 kB 3.1 MB/s 
     |████████████████████████████████| 63 kB 1.9 MB/s 
     |████████████████████████████████| 80 kB 8.6 MB/s 
     |████████████████████████████████| 68 kB

In [2]:
import requests

In [5]:
def lookup(word):
  url = "https://www.moedict.tw/a/"
  data=requests.get(url+word+".json").json()
  return data['English']

In [6]:
lookup("教室")

'classroom'

In [9]:
import gradio

In [10]:
gradio.Interface(lookup, "text", "text", title="漢英字典").launch(share=True)

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://49507.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)


(<gradio.routes.App at 0x7fb2739b5b10>,
 'http://127.0.0.1:7860/',
 'https://49507.gradio.app')

```python
import numpy as np
```python
import matplotplotlib.pyplot asplt
```python
import pandas aspd

## 基本語法
* 迴圈loops =>for,while
*函式 (functions)
*條件式(if statements)
*例外處理(exception handling)


###例外處理

In [32]:
def add(x,y):
  print(f"{x}+{y}={x+y}")

def sub(x,y):
  print(f"{x}-{y}={x-y}")

def mul(x,y):
  print(f"{x}x{y}={x*y}")

def div(x,y):
  print(f"{x}/{y}={x/y}")

In [33]:
functions=[add,div,mul,sub]

In [34]:
x=4
y=2
for func in functions:
  func(x,y)

4+2=6
4/2=2.0
4x2=8
4-2=2


In [36]:
x=4
y=0
for func in functions:
  try:
    func(x,y)
  except Exception as e:
    print(e.args)

4+0=4
('division by zero',)
4x0=0
4-0=4


In [27]:
add(2,1)

2+1=3


# 資料分析簡介
* Numpy
  * Numerical Python
  * 科學運算基礎套件
* MatPlotLib
  * Matrix Plotting 
  * 繪圖基礎套件
* Pandas
  * Panel Data
  * 資料分析基礎套件

# Numpy
 * new data type
  * ndarray==>Multi-Dementional Array
* new functions to process data
  * ufunc==>Universal Functions

## 使用原生的Python執行向量運算時會遇到的問題

In [12]:
x1=[1,2,3]
x2=[4,5,6]


In [13]:
x1+x2

[1, 2, 3, 4, 5, 6]

In [14]:
2*x1

[1, 2, 3, 1, 2, 3]

In [19]:
list(zip(x1, x2))

[(1, 4), (2, 5), (3, 6)]

In [17]:
x3=[]
for i,j in zip(x1, x2):
  x3.append(i+j)

In [18]:
x3

[5, 7, 9]

#Numpy用來做甚麼?

### ndarray ==> 多維陣列

In [37]:
import numpy as np

In [38]:
x1

[1, 2, 3]

In [39]:
x2

[4, 5, 6]

In [40]:
y1=np.array(x1)
y2=np.array(x2)

In [41]:
y1+y2

array([5, 7, 9])

In [42]:
2*y1

array([2, 4, 6])

### ufunc==> 通用函式


In [43]:
# 在原生的python中
import math

In [44]:
math.sin(math.pi/2)

1.0

In [45]:
math.sin(x1)

TypeError: ignored

In [47]:
# 在numpy中
np.sin(np.pi/2)

1.0

In [48]:
np.sin(x1)

array([0.84147098, 0.90929743, 0.14112001])

### 甚麼地方甚麼地方會用到ndarray?

In [49]:
import cv2

In [50]:
import matplotlib.pyplot as plt


# 如何用Python畫地圖

LBS:Location-Based Service

Folium 快速入門
  https://python-visualization.github.io/folium/quickstart.html

In [23]:
import folium
m = folium.Map(location=[45.5236, -122.6750])

In [53]:
m

In [59]:
m = folium.Map(location=[22.6273, 120.3014],zoom_start=16)

In [60]:
m

In [61]:
# 存成網頁
m.save("index.html")

In [62]:
m = folium.Map(location=[22.6273, 120.3014],zoom_start=16)
folium.Marker([22.6273, 120.3014],popup="高雄市").add_to(m)

In [63]:
m

## 使用geocoder查詢GPS座標
https://geocoder.readthedocs.io/

In [22]:
import geocoder

ModuleNotFoundError: ignored

In [26]:
!pip install geocoder

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 98 kB 6.5 MB/s 


In [69]:
geocoder.osm("台北市").latlng

[25.0375198, 121.5636796]

In [21]:
place="楠梓加工區"
gps=geocoder.osm(place).latlng
m = folium.Map(location=gps,zoom_start=16)
folium.Marker(gps,popup=place).add_to(m)
m

NameError: ignored

In [71]:
m

In [80]:
def draw_map(place):
  
  gps=geocoder.osm(place).latlng
  m = folium.Map(location=gps,zoom_start=16)
  folium.Marker(gps,popup=place).add_to(m)
  return m

In [82]:
draw_map("高雄技擊館")

## 練習:到政府資料開放平台，下載Ubike站點資料，將之畫在地圖上

https://data.gov.tw/dataset/137993

https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json

In [5]:
import requests

In [9]:
url="https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json"

In [10]:
data=requests.get(url).json()

In [88]:
type(data)

list

In [89]:
data[0]

{'act': '1',
 'ar': '復興南路二段235號前',
 'aren': 'No.235， Sec. 2， Fuxing S. Rd.',
 'bemp': 25,
 'infoDate': '2022-07-16',
 'infoTime': '2022-07-16 11:51:37',
 'lat': 25.02605,
 'lng': 121.5436,
 'mday': '2022-07-16 11:51:37',
 'sarea': '大安區',
 'sareaen': 'Daan Dist.',
 'sbi': 3,
 'sna': 'YouBike2.0_捷運科技大樓站',
 'snaen': 'YouBike2.0_MRT Technology Bldg. Sta.',
 'sno': '500101001',
 'srcUpdateTime': '2022-07-16 11:55:12',
 'tot': 28,
 'updateTime': '2022-07-16 11:55:24'}

### 練習1.請使用for迴圈print出所有站點名稱及GPS座標
### 練習2.請在地圖上標出所有站點位置及名稱

In [11]:
for x in data:
  print(f"{x['sna']}==>({x['lat']},{x['lng']})")

YouBike2.0_捷運科技大樓站==>(25.02605,121.5436)
YouBike2.0_復興南路二段273號前==>(25.02565,121.54357)
YouBike2.0_國北教大實小東側門==>(25.02429,121.54124)
YouBike2.0_和平公園東側==>(25.02351,121.54282)
YouBike2.0_辛亥復興路口西北側==>(25.02153,121.54299)
YouBike2.0_復興南路二段280號前==>(25.02429,121.54328)
YouBike2.0_復興南路二段340巷口==>(25.02253,121.54326)
YouBike2.0_新生南路三段52號前==>(25.02112,121.53407)
YouBike2.0_新生南路三段66號前==>(25.01976,121.53384)
YouBike2.0_新生南路三段82號前==>(25.01894,121.53361)
YouBike2.0_辛亥路一段30號前==>(25.01986,121.52982)
YouBike2.0_和平復興路口西北側==>(25.02543,121.54332)
YouBike2.0_羅斯福路三段311號前==>(25.01717,121.53202)
YouBike2.0_大安運動中心停車場==>(25.020348,121.546446)
YouBike2.0_羅斯福路三段245號前==>(25.01927,121.52989)
YouBike2.0_羅斯福路三段269巷5號前==>(25.01913,121.53079)
YouBike2.0_溫州公園==>(25.01895,121.53156)
YouBike2.0_和平臥龍街口==>(25.024461,121.546705)
YouBike2.0_溫州停車場==>(25.02093,121.5331)
YouBike2.0_銘傳國小側門==>(25.01385,121.53549)
YouBike2.0_捷運公館站(2號出口)==>(25.01491,121.53438)
YouBike2.0_第二學生活動中心==>(25.01244,121.53661)
YouBike2.0_臺灣科技大學正門==>(25.01451,

In [28]:
import geocoder

In [29]:
def draw_map(place):
  
  gps=geocoder.osm(place).latlng
  m = folium.Map(location=gps,zoom_start=16)
  folium.Marker(gps,popup=place,icon=folium.Icon(color="red")).add_to(m)
  return m

In [31]:
m = draw_map("台北市")
m

In [33]:
for x in data:
  folium.Marker([x['lat'],x['lng']], popup=x['sna']).add_to(m)

In [34]:
m